--[[
    Humans: Are Weak - attach an icon to every trait definition.

    WHY THIS FILE EXISTS. A trait with no texture is invisible in both panels
    that list traits, and neither one tells you why:

      ISCharacterScreen.setDisplayedTraits  `if ... and definition:getTexture() then`
      ISPlayerStatsUI.loadTraits            `if trait and trait:getTexture() then`

    Both silently skip the trait. That is why H:AW's traits were applied to the
    character - console.txt showed "TraitZ shaw:adhd" and the ADHD effects all
    fired - while the character screen and the admin panel both showed an empty
    trait list.

    It is not a modding mistake so much as a vanilla gap: CharacterTraitDefinition
    references `media/ui/Traits/trait_generic.png` as a fallback, and that file
    **does not ship**. The folder holds 16 icons for roughly 90 vanilla traits,
    so most vanilla traits are invisible in those panels too.

    WHY setTexture RATHER THAN A FILENAME. The engine derives an icon path as
    `media/ui/Traits/trait_` + name + `.png`, lower-cased. What exactly it uses
    for `name` on a modded `SHAW:adhd` is not documented, and if it is the full
    id then the derived filename contains a colon - which cannot exist on
    Windows. Rather than guess, this sets the texture explicitly.
    CharacterTraitDefinition is annotated @UsedFromLua and exposes setTexture,
    so this is a supported call, not a trick.

    Icons live at media/ui/Traits/trait_SHAW_<id>.png and are generated by
    tools/maketraiticons.py.
]]

SHAW = SHAW or {}

local ICON_PATH = "media/ui/Traits/trait_SHAW_%s.png"

local function attachIcons()
    local attached, missing = 0, 0

    for _, id in pairs(SHAW.traitIds()) do
        local handle = CharacterTrait[string.upper(id)]
        if handle then
            local ok = pcall(function()
                local definition = CharacterTraitDefinition.getCharacterTraitDefinition(handle)
                if not definition then
                    missing = missing + 1
                    return
                end

                -- Do not overwrite an icon someone else already set.
                if definition:getTexture() then
                    attached = attached + 1
                    return
                end

                local texture = getTexture(string.format(ICON_PATH, id))
                if texture then
                    definition:setTexture(texture)
                    attached = attached + 1
                else
                    missing = missing + 1
                    print("[SHAW] no icon at " .. string.format(ICON_PATH, id))
                end
            end)

            if not ok then
                missing = missing + 1
            end
        end
    end

    SHAW.log("icons: %d attached, %d missing", attached, missing)
end

-- OnGameStart, not OnGameBoot: the trait definitions are built from the script
-- files during boot, so asking for one earlier can find nothing. Running it
-- again on OnCreatePlayer is harmless - it no-ops once a texture is set - and
-- covers a definition rebuilt between characters.
Events.OnGameStart.Add(attachIcons)
Events.OnCreatePlayer.Add(attachIcons)
